/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:69425564-1577-453c-a5d2-8a36ddadda1d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_5n1es9jIg",
    "aws_user_pools_web_client_id": "2fao57hpgiu0c0p15idjoovk95",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://2bodhoipfjfmvefjwggybkcara.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
